version: "3"
services:
  windows:
    image: dockur/windows
    container_name: windows_rdp_custom
    environment:
      - VERSION=win11
      - RAM_SIZE=8G
      - CPU_CORES=4
      - DISK_SIZE=64G
      # Логин и пароль для входа
      - USERNAME=user
      - PASSWORD=mypassword
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      # Внешний порт 5901 -> Внутренний порт 3389 (RDP)
      - 5901:3389
      # Оставляем веб-порт для контроля установки
      - 8006:8006
    volumes:
      - ./win_data:/storage
    stop_grace_period: 2m
    restart: on-failure
